
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PUGUH
 */
public class frmMain extends javax.swing.JFrame {
    int total;

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenis = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        kasir = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        STR = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pesanan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        mak = new javax.swing.JRadioButton();
        min = new javax.swing.JRadioButton();
        jumlah = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        hargatot = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tunai = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdiskon = new javax.swing.JTextArea();
        hasil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        print1 = new javax.swing.JButton();
        proses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Mbak Tum's");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(510, 50, 260, 70);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("WARUNG MAKAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(440, 40, 230, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, -20, 1220, 140);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasirActionPerformed(evt);
            }
        });
        jPanel2.add(kasir);
        kasir.setBounds(120, 30, 210, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Kasir :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 30, 60, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tanggal");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 80, 130, 30);
        jPanel2.add(tanggal);
        tanggal.setBounds(120, 80, 210, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Kode Struk");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(40, 130, 130, 30);
        jPanel2.add(STR);
        STR.setBounds(120, 130, 210, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(410, 140, 380, 190);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Pesanan :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(40, 20, 60, 30);

        pesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesananActionPerformed(evt);
            }
        });
        jPanel3.add(pesanan);
        pesanan.setBounds(120, 20, 210, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Jenis :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(90, 60, 60, 30);

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel3.add(harga);
        harga.setBounds(160, 140, 170, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Harga :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(90, 140, 60, 30);

        jenis.add(mak);
        mak.setText("Makanan");
        mak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makActionPerformed(evt);
            }
        });
        jPanel3.add(mak);
        mak.setBounds(160, 60, 80, 30);

        jenis.add(min);
        min.setText("Minuman");
        jPanel3.add(min);
        min.setBounds(250, 60, 90, 30);

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        jPanel3.add(jumlah);
        jumlah.setBounds(160, 100, 170, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Jumlah");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(90, 100, 60, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 140, 380, 190);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        hargatot.setEditable(false);
        hargatot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargatotActionPerformed(evt);
            }
        });
        jPanel4.add(hargatot);
        hargatot.setBounds(150, 20, 180, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Harga Total");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(40, 20, 110, 30);

        diskon.setEditable(false);
        jPanel4.add(diskon);
        diskon.setBounds(150, 120, 180, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Diskon");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(40, 120, 110, 30);

        bayar.setEditable(false);
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        jPanel4.add(bayar);
        bayar.setBounds(150, 170, 180, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Bayar");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(40, 170, 110, 30);

        tunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunaiActionPerformed(evt);
            }
        });
        jPanel4.add(tunai);
        tunai.setBounds(150, 260, 180, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Tunai");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(40, 260, 110, 30);

        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });
        jPanel4.add(kembalian);
        kembalian.setBounds(150, 310, 180, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Kembalian");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(40, 310, 110, 30);

        txtdiskon.setColumns(20);
        txtdiskon.setRows(5);
        jScrollPane2.setViewportView(txtdiskon);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(60, 60, 270, 50);

        hasil.setText("Hasil");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        jPanel4.add(hasil);
        hasil.setBounds(200, 220, 55, 23);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(800, 140, 380, 360);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STR", "Kasir", "Tanggal", "Pesanan", "Jenis", "Jumlah", "Harga", "Hargatot", "Diskon", "Bayar", "Tunai", "Kembalian"
            }
        ));
        jScrollPane1.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 510, 1160, 170);

        delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(340, 420, 120, 40);

        exit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(640, 420, 120, 40);

        save.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(40, 420, 120, 40);

        clear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(190, 420, 120, 40);

        print1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        print1.setText("Print");
        print1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print1ActionPerformed(evt);
            }
        });
        getContentPane().add(print1);
        print1.setBounds(490, 420, 120, 40);

        proses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        proses.setText("Proses Pembelian");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(290, 350, 220, 50);

        setBounds(0, 0, 1216, 740);
    }// </editor-fold>//GEN-END:initComponents

    private void pesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesananActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void tunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tunaiActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasirActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_kasirActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if("".equals(STR.getText()) || "".equals(kasir.getText()) || 
                "".equals(tanggal.getText()) ||
            "".equals(pesanan.getText()) || "".equals(harga.getText()) || "".equals(jumlah.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error",
                JOptionPane.WARNING_MESSAGE);
        } else {
            String jenis = "";
            if (mak.isSelected()){
                jenis = "Makanan";
            } else {
                jenis = "Minuman";
            }
            
            
            String SQL = "INSERT INTO tb_resto (STR,Kasir,Tanggal,Pesanan,Jenis,Jumlah,Harga,Hargatot,Diskon"
            + "Bayar,Tunai,Kembalian)VALUES('"+kasir.getText()+"','"
            +tanggal.getText()+"','"+jenis+"','"+pesanan.getText()+"','"+
            harga.getText()+"','"+hargatot.getText()+"','"+diskon.getText()+
                    "','"+bayar.getText()+"','"+tunai.getText()+"','"
                    +kembalian.getText()+"')";
            int status = 0;
            try {
                status = KoneksiDB.execute(SQL);
            } catch (SQLException ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan",
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
                try {
                    selectData();
                } catch (SQLException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan",
                    "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        STR.setText("");
        kasir.setText("");
        tanggal.setText("");
        pesanan.setText("");
        jenis.clearSelection();
        jumlah.setText("");
        harga.setText("");
        hargatot.setText("");
        diskon.setText("");
        bayar.setText("");
        tunai.setText("");
        kembalian.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_exitActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int baris = tabel.getSelectedRow();
        if (baris != -1) {
            String NIS = tabel.getValueAt(baris, 0).toString();
            String SQL = "Delete FROM tb_resto WHERE STR='"+STR+"'";
            int status = 0;
            try {
                status = KoneksiDB.execute(SQL);
            } catch (SQLException ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus",
                    "Sukses",JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus",
                    "Gagal",JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih "
                + "Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void hargatotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargatotActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hargatotActionPerformed

    private void print1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_print1ActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        // TODO add your handling code here:
        int lah;
        int ga;
        lah = Integer.parseInt(jumlah.getText());
        ga = Integer.parseInt(harga.getText());
        
        int total = lah*ga;
        int batot = total-(total*15/100);
        hargatot.setText(""+total);
        
        if(total >= 20000){
            txtdiskon.setText("Selamat! Anda mendapat diskon dengan \n minimal pembelian Rp.20000");
            diskon.setText("15%");
            bayar.setText(""+batot);
        } else {
            txtdiskon.setText("");
        }
    }//GEN-LAST:event_prosesActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void makActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField STR;
    private javax.swing.JTextField bayar;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField diskon;
    private javax.swing.JButton exit;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField hargatot;
    private javax.swing.JButton hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jenis;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kasir;
    private javax.swing.JTextField kembalian;
    private javax.swing.JRadioButton mak;
    private javax.swing.JRadioButton min;
    private javax.swing.JTextField pesanan;
    private javax.swing.JButton print1;
    private javax.swing.JButton proses;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField tunai;
    private javax.swing.JTextArea txtdiskon;
    // End of variables declaration//GEN-END:variables

    private void selectData() throws SQLException {
        String kolom[] = {"STR","Kasir","Tanggal","Pesanan","Jenis","Jumlah",
            "Harga","Hargatot","Diskon","Bayar","Tunai","Kembalian"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_resto";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String JenisKelamin = "";
                if ("L".equals(rs.getString(3))){
                    JenisKelamin = "Laki-Laki";
                } else {
                    JenisKelamin = "Perempuan";
                }
                String Kelas = rs.getString(4);
                String Email = rs.getString(5);
                String Alamat = rs.getString(6);
                String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabel.setModel(dtm);
    }
}
